### ISSUE TITLE
Feature request: option to annotate IS elements in complete genomes

### ISSUE THREAD

**Issue by alexweisberg** [joshuakirsch/pseudoR#5]
Hi, 

This pipeline and new IS element database look to be a great resource. I couldn't tell from the manuscript and documentation, but I was wondering if it would be possible to add a mode where it identifies the IS element regions and borders in completely assembled genomes, without the use of reads?

I.e. The user inputs a genome assembly (even an already annotated one, perhaps gbk or gff3 file?), and the software searches for IS elements and identifies IS element regions and borders within the assembly. This would be a little different from the current mode, which, as far as I understand it, identifies new IS element insertions relative to a strain that previously did not have them?

Thanks!

**Comment by joshuakirsch** [comment]
Hi,

Thanks for checking out the tool! pseudoR is better suited to finding new IS insertions in previously assembled data where heterogeneous IS insertions are omitted or poorly assembled. My advice for finding IS insertions in complete genomes is to use OASIS ([https://github.com/dgrtwo/OASIS/tree/master]). For our database, we used OASIS to mine through all complete microbial genomes on NCBI and found that it was very good at identifying complete elements in genomes. Hope this helps! IS elements can be cross-referenced in our database or ISFinder.

**Comment by alexweisberg** [comment]
Thanks for the suggestion. As you mentioned, it is difficult to download or distribute the ISFinder database. Do you know if OASIS is compatible with the ISOSDB database, or if it needs to be reformatted?

**Comment by joshuakirsch** [comment]
OASIS doesn't require an IS database. It works by finding annotated transposases in annotated genbank files, then looks for inverted repeats and sequence homology surrounding the IS elements.  Check out the paper here for more information: https://academic.oup.com/nar/article/40/22/e174/1139563
