### ISSUE TITLE
Error in R script in single-reference model

### ISSUE THREAD

**Issue by miniluphy** [joshuakirsch/pseudoR#6]
After I installed the virtual environment of pseudoR by conda, I removed the `-3` option and directly called the pseudoR_single-reference.sh script. 

The command is as follows, but it resulted in an error, seemingly within the R script. Below are the command, the generated files and log files.

Could you help me identify where the problem might be? 

`source pseudoR_single-reference.sh -s list.strain -d  /home/user/software/pseudoR -c reads -m s  -r ref.fasta -t 8  -1  '.read1.fq.gz' -2 '.read2.fq.gz'`

Thank you.

[log.txt](https://github.com/joshuakirsch/pseudoR/files/14978806/log.txt)
[result.tree.txt](https://github.com/joshuakirsch/pseudoR/files/14978807/result.tree.txt)

**Comment by joshuakirsch** [comment]
Hi! Thanks for trying out pseudoR and I'm sorry about the errors.. Can you possibly attach `C8092.unmapped.contig_mapping.filtered.sam`, `C8092_pre_mapping_output.csv`, and `list.strain` ? Thanks!

**Comment by miniluphy** [comment]
Thank you for your response！
Attached, please find the document you mentioned. I hope it proves helpful.
[AttachedFile.zip](https://github.com/joshuakirsch/pseudoR/files/14981538/AttachedFile.zip)

**Comment by joshuakirsch** [comment]
Thanks for these! I've gone through the files you provided and I unfortunately think the reason you are getting this error is that there aren't any strongly supported IS insertions in this sample. There are a number of trimmed reads that were remapped with 3' terminus of ISOSDB6215 or ISOSDB4244. However, there were no trimmed reads with the 5' terminus of either of these IS elements. To ensure that IS insertions are bonafide, only loci where trimmed reads with the both 3' and 5' termini (some reads have 3' termini and some reads have 5' termini) are reported as insertions. During my development of the program, I found that reporting loci where only one type of termini mapped lead to spurious results. I will update the repo at some point in near future to make this explained as an error in program. Thanks again for trying pseudoR and let me know if there is anything else I can help with.

**Comment by miniluphy** [comment]
Thank you for your response. 
It appears that indeed my current sample didn’t detect the IS insertions. I tried another sample and was able to detect them. This tool is designed to detect genomic IS insertions based on metagenomic data. 
Could you please provide insight into whether it’s possible to enumerate the types and quantities of IS elements within the metagenomic or illumina data? This is a matter of particular concern for me.
Thank you！

**Comment by joshuakirsch** [comment]
Glad it worked! This tool is designed primarily to identify sites where both an un-inserted allele and an IS inserted allele exist. For instance, this tool can find a novel, unidentified IS insertion in a gene that was previously assembled without an IS insertion. In the tool's output, you will be given the IS identified (ISOSDBXXX) and the likely IS family. The ISOSDB number is unique identifier for that IS element. You can profile these further if you want by pulling out the sequence of the IS element from the ISOSDB database. Let me know if there is anything else I can help with!

**Comment by miniluphy** [comment]
Thank you for your response and advices！
