### ISSUE TITLE
 Identification of IS Element Insertion Sites and Impact Analysis on Gene Structure

### ISSUE THREAD

**Issue by 2021JohnSheng** [joshuakirsch/pseudoR#8]
Hi,
I would like to inquire about the methodology for accurately determining whether an insertion sequence (IS) element is inserted within a gene or in an intergenic region. This distinction is critical for downstream analyses, particularly in the context of understanding the functional consequences of IS insertions on gene integrity.

In cases where the IS element is found to be inserted within a gene, there arises the challenge of effectively analyzing the disrupted gene. Specifically, the insertion may compromise the integrity of the open reading frame (ORF), leading to the potential misprediction of ORFs. The original continuous ORF could be erroneously predicted as two separate ORFs due to the IS insertion.

Could you provide guidance or recommend approaches for:

1. Identifying the precise location of IS insertions relative to gene boundaries.
2. Assessing the functional implications of such insertions on disrupted genes, particularly regarding ORF prediction and analysis.

Thank you for your attention to this matter.

Best regards,
Yong Sheng

**Comment by joshuakirsch** [comment]
Hi Yong Sheng,

Thanks for the interest in the tool!

1. IS insertion locations provided by the tool in the final products should be precise enough to identify whether the insertion occurs in a gene or not. I've built two different methods to find IS insertions in ORFs into this tool. The first is the last column in `final_results/pseudoR_output.contig.tsv`. This column should display the ORF if the IS insertion was found to be an intragenic insertion. These intragenic insertions are found by seeing if IS insertions occur in a list of predicted ORFs from the reference contigs. These ORFs are predicted using prodigal in meta mode. The other method to find IS insertions in ORFs is where the pipeline is run only on ORF sequences. The results of this analysis are found in `final_results/pseudoR_output.ORF.tsv`. Any insertion found here can be thought of as occuring inside of an ORF.
2. This is a tricky question. In the paper, we used the heuristic that any IS insertion in an ORF inactivated the gene product. This is a rough approximation. 

Hope this helps!
Josh

**Comment by 2021JohnSheng** [comment]
> Hi Yong Sheng,
> 
> Thanks for the interest in the tool!
> 
> 1. IS insertion locations provided by the tool in the final products should be precise enough to identify whether the insertion occurs in a gene or not. I've built two different methods to find IS insertions in ORFs into this tool. The first is the last column in `final_results/pseudoR_output.contig.tsv`. This column should display the ORF if the IS insertion was found to be an intragenic insertion. These intragenic insertions are found by seeing if IS insertions occur in a list of predicted ORFs from the reference contigs. These ORFs are predicted using prodigal in meta mode. The other method to find IS insertions in ORFs is where the pipeline is run only on ORF sequences. The results of this analysis are found in `final_results/pseudoR_output.ORF.tsv`. Any insertion found here can be thought of as occuring inside of an ORF.
> 2. This is a tricky question. In the paper, we used the heuristic that any IS insertion in an ORF inactivated the gene product. This is a rough approximation.
> 
> Hope this helps! Josh

Dear Josh,

Thank you for your valuable insights regarding the identification of insertion sequence (IS) elements and their effects on gene integrity.

I would like to discuss my proposed methodology for analyzing IS insertions based on known genomic coordinates and would appreciate your feedback on its validity.

First, I will determine the precise locations of the IS elements within the genome by using the coordinates I already possess. To facilitate the analysis, I plan to annotate the genome using Prokka. This will allow me to identify the coding sequences (CDS). After obtaining the CDS information from the Prokka annotation, I will extract the coordinates of the CDS regions. The next step involves comparing the coordinates of the CDS regions with the coordinates of the IS insertions. By checking for overlaps or intersections, I can determine whether the IS elements are inserted within a gene (i.e., in the CDS region) or in intergenic regions.

Based on this analysis approach, do you think this methodology is appropriate for accurately determining the location of IS insertions relative to genes?
Are there any additional considerations or alternative methods you would recommend for evaluating the functional consequences of IS insertions on CDS regions?
I believe this approach will help elucidate the impact of IS insertions on gene functionality, and I would greatly value your expertise on this matter.

Thank you once again for your assistance.

Best regards,
Yong Sheng

**Comment by joshuakirsch** [comment]
Hi Yong Sheng,

I think your approach will work! For this analysis, make sure to use the information in  `final_results/pseudoR_output.contig.tsv`. 

Hope you find interesting results and let me know if I can help with anything else.

Josh
