### ISSUE TITLE
Failing post-analysis_V3 and Final_Output.multiReference.R 

### ISSUE THREAD

**Issue by cifuj** [joshuakirsch/pseudoR#9]
Hi Joshua, thanks for the great pipeline and conceptual idea of identifying insertion sequences from the metagenomes.
I am trying to run your pipeline on bacteria that have multiple transposase on their genomes, but I would like to know if there are any IS that are not captured in the genome or that are potentially "active" IS. 

I ran the whole pipeline, but it failed in the post-analysis_V3 and Final_Output.multiReference.R  steps. It produced a couple of outputs, but not all of them and I am not sure why or how to explain it. [error_log_pseudofinder.txt](https://github.com/user-attachments/files/16458427/error_log_pseudofinder.txt)

Can I look at some specific output to tell if the pipeline ran through? 

These are the files in the `final_results` folder

```
==> IS_hits_in_orfs.txt <==

==> orf_analysis.bed <==
Sample_4132AR_000000000236_6	294	295

==> orf_analysis.step1.tsv <==
sample	IS	contig	insertion_pos	5prime	3prime	max_depth_site_insertion_pos	max_depth_site_depth	IS_type	itr	max_itr
Sample_4025BE	ISOSDB8833	Sample_4132AR_000000000236_6	295	2	1	295	2	ISOSDB8833	196	196

==> orf_IS_hits.txt <==
Sample_4132AR_000000000236_6
```

Thanks!
Jero

**Comment by joshuakirsch** [comment]
Hi Jero,

Thanks for trying out the tool. Sorry the error messages are inscrutable and it's on my list to improve these at some point. Would you mind sharing the contents of the files in the mapping_files folder ending in `unmapped.contig_mapping.filtered.sam` and `_pre_mapping_output.csv`? 

Thanks,
Josh

**Comment by cifuj** [comment]
Hi Josh, thanks for the quick reply.
Here are the files [mapping_files.tar.gz](https://github.com/user-attachments/files/16467081/mapping_files.tar.gz)

Best,
Jero

**Comment by joshuakirsch** [comment]
Hi Jero,

I've looked through your files and I think that the program failed because there wasn't enough data to find high confidence IS insertions with information from both the 3' and 5' end of an IS element. If you want to tell me more about your experiment (sample origin, depth sequenced, etc.) I might be able to suggest changes that could to better IS detection.

Thanks and sorry about my bummer of an answer,
Josh

**Comment by cifuj** [comment]
Hi Josh, thanks for looking into my results. I am quite puzzled by the fact that there are no IS in these genomes. They are full of transposases and they are actively transcribed. They are bacterial symbionts (animal-microbe) and are deeply covered in these metagenomes around 200 to 500x. 
I tried OASIS in another genome of the same species and I got some results but not a proper classification, and even some have inverted repeats [oasis_test.txt](https://github.com/user-attachments/files/16495649/oasis_test.txt) I think that there is something hehehe
I would appreciate any advice. 

Best,
Jero

**Comment by joshuakirsch** [comment]
Hi Jero, just to clarify that pseudoR detects movement of IS elements, not the presence of IS elements. One possibility could be that the IS elements in your samples are not present in the ISOSDB. As a test, you could extract one IS element from `set_id "13"` and blast it against the ISOSDB provided in the repo. If there isn't a strong hit, I can help you build a new IS database that could be used with pseudoR.

How deep are the samples sequenced in terms of millions of reads?

Thanks for using the program!
Josh

**Comment by cifuj** [comment]
Hi Josh. Yes, sorry I did not mean that pseudoR identifies the presence of IS elements, I was putting the OASIS results here to comment on how abundant the IS are, and I am curious about how they can be abundant but could not detect any IS moving. 
I did as you said and compared all the IS detected by OASIS on my genome against the ISOSDB.V3.fna. As you anticipated, there were no strong hits against the ISODB. 
I would appreciate your help in building a custom IS database to use then pseudorR. I was checking the file `extra_files/deNovo_IS_Identification.sh` and it uses `isescan.py`. I tried using isescan before and it failed as there where too many hits in the genome, and I could not detect ISs with this software. 
Can I try using the ISs detected by OASIS that contain IR sequences? or even all the IS detected by OASIS?

In terms of reads, my samples will contain between 12 to 25 million paired-end reads.

Thanks for all your help!
Jero

**Comment by joshuakirsch** [comment]
Hi Jero,

Sorry for the slower reply. I'll make a script that will produce a new database in the next few days and release an update to the repo. The `extra_files/deNovo_IS_Identification.sh` is a relic from an older version of this program. I'll post another comment when I have the script done.

**Comment by joshuakirsch** [comment]
Hey Jero,

I uploaded the file `Generate_IR_Database.sh` file to the repo. This program will generate a new blast database from a fasta file of IS elements. You will need to have CD-hit installed to run this program. When you run pseudoR, make sure the change the location of the IR database to this new database. Let me know if there is any issues and if there are any cool results!

Thanks,
Josh

**Comment by cifuj** [comment]
Thank you so much Josh! 
As you suspected,  the IS elements in my samples were absent in the ISOSDB. I built a new IR with the script you wrote and now I can identify the IS in my genomes 😄
